set-option -sa terminal-overrides ",xterm*:Tc"
set -g cursor-style bar
set -g mouse on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n C-Left if-shell "ps -o state=,comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?\\.?(view|l?n?vim?x?)(diff)?(-wrapped)?$'" "send-keys M-h" "resize-pane -L 2"
bind -n C-Down if-shell "ps -o state=,comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?\\.?(view|l?n?vim?x?)(diff)?(-wrapped)?$'" "send-keys M-j" "resize-pane -D 2"
bind -n C-Up if-shell "ps -o state=,comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?\\.?(view|l?n?vim?x?)(diff)?(-wrapped)?$'" "send-keys M-k" "resize-pane -U 2"
bind -n C-Right if-shell "ps -o state=,comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?\\.?(view|l?n?vim?x?)(diff)?(-wrapped)?$'" "send-keys M-l" "resize-pane -R 2"

set -g @catppuccin_flavour 'mocha'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'

bind 's' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
